name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  shared_preferences: ^2.3.2
  image_picker: ^1.0.7
  flutter_animate: ^4.5.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  lottie: ^2.7.0
  sqflite_common_ffi: ^2.3.2
  url_launcher: ^6.3.2
  material_symbols_icons: ^4.2721.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  carousel_slider: ^4.2.1
  animate_do: ^3.3.4
  cached_network_image: ^3.3.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  local_auth: ^2.1.7
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.9.0
  image: ^4.2.0
  http: ^1.2.2
  tflite_flutter: ^0.11.0
  permission_handler: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/dokter1.png
    - assets/images/dokter2.png
    - assets/images/dokter3.png
    - assets/images/aura1.jpg
    - assets/images/aura2.jpg
    - assets/images/instagram.png
    - assets/images/whatsapp.png
    - assets/images/tiktok.png
    - assets/images/faceid.png
    - assets/success.json
    - assets/face_detect.json
    - assets/models/facenet.tflite
